#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Replacer(object):
    def setupUi(self, Replacer):
        Replacer.setObjectName("Replacer")
        Replacer.resize(825, 506)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        Replacer.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(Replacer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 10, 461, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.typeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.gridLayout.addWidget(self.typeLabel, 2, 0, 1, 1)
        self.fromLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fromLabel.setObjectName("fromLabel")
        self.gridLayout.addWidget(self.fromLabel, 0, 0, 1, 1)
        self.toLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.toLine.setObjectName("toLine")
        self.gridLayout.addWidget(self.toLine, 1, 1, 1, 1)
        self.toLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.toLabel.setObjectName("toLabel")
        self.gridLayout.addWidget(self.toLabel, 1, 0, 1, 1)
        self.fromLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.fromLine.setObjectName("fromLine")
        self.gridLayout.addWidget(self.fromLine, 0, 1, 1, 1)
        self.typeLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.typeLine.setObjectName("typeLine")
        self.gridLayout.addWidget(self.typeLine, 2, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Replacer)
        self.textBrowser.setGeometry(QtCore.QRect(55, 171, 731, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Replacer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(550, 90, 231, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.quitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)

        self.retranslateUi(Replacer)
        QtCore.QMetaObject.connectSlotsByName(Replacer)

    def retranslateUi(self, Replacer):
        _translate = QtCore.QCoreApplication.translate
        Replacer.setWindowTitle(_translate("Replacer", "Form"))
        self.typeLabel.setText(_translate("Replacer", "File Type   :"))
        self.fromLabel.setText(_translate("Replacer", " Directory to look for   : "))
        self.toLine.setToolTip(_translate("Replacer", "<html><head/><body><p>Optional</p></body></html>"))
        self.toLine.setWhatsThis(_translate("Replacer", "<html><head/><body><p>Creates a folder in search directory if left blank.</p></body></html>"))
        self.toLabel.setText(_translate("Replacer", " Directory to save files:"))
        self.fromLine.setToolTip(_translate("Replacer", "<html><head/><body><p>Neccesary.</p></body></html>"))
        self.fromLine.setWhatsThis(_translate("Replacer", "<html><head/><body><p>Warning!! Replaces given type files under the directory.</p><p>Do not give a root directory.</p></body></html>"))
        self.typeLine.setToolTip(_translate("Replacer", "<html><head/><body><p>Neccesary</p></body></html>"))
        self.typeLine.setWhatsThis(_translate("Replacer", "<html><head/><body><p>Please enter the extension of files u want to replace.</p></body></html>"))
        self.startButton.setText(_translate("Replacer", "Start"))
        self.quitButton.setText(_translate("Replacer", "Quit"))
